### ISSUE TITLE
Error on Launching app

### ISSUE THREAD

**Issue by felipeparente** [davidsdearaujo/select_dialog#45]
i`m using Flutter 3.13.1
In my app, is showing the error bellow:

Error: No named parameter with the name 'isAlwaysShown'.
select_dialog.dart:218
                  isAlwaysShown: widget.alwaysShowScrollBar,
                  ^^^^^^^^^^^^^
: Context: Found this candidate, but the arguments don't match.
scrollbar.dart:87

  const Scrollbar({
        ^^^^^^^^^

**Comment by graux** [comment]
The issue has been solved and merged, but the version has not been released. (waiting on the package owner)

For the time being you replace in your `pubspec.yaml` this code:
```
select_dialog: ^2.0.0
```
and use this instead:
```
  select_dialog:
    git:
      url: https://github.com/davidsdearaujo/select_dialog.git
      ref: master
```

Once 2.0.1 has been released, then you can use the package version instead.
Cheers!
